#!/bin/sh

# Regenerate all files which are constructed by the autoconf and automake
# tool-chain. Note: only developers should need to use this script.

# Author: Morten Eriksen, <mortene@sim.no>.

# Makes it possible to run this script from any location.
directory=`echo "$0" | sed -e 's/[^\/]*$//g'`;
cd $directory
if test ! -f ./bootstrap; then
  echo "unexpected problem with your shell - bailing out"
  exit 1
fi

AUTOCONF_VER=2.52
AUTOMAKE_VER=1.5

DIE=false

PROJECT=IvTools
MACRODIR=cfg/m4
AUTOMAKE_ADD=

if test "$1" = "--clean"; then
  rm -f aclocal.m4 \
	config.guess \
	config.h.in \
	config.sub \
	configure \
	depcomp \
	install-sh \
	missing \
	mkinstalldirs \
	stamp-h*
  find . -name Makefile.in -print | xargs rm -f
  exit 0
elif test "$1" = "--add"; then
  AUTOMAKE_ADD="--add-missing --copy"
fi

echo "Checking the installed configuration tools..."

if test -z "`autoconf --version 2>/dev/null | grep \" $AUTOCONF_VER\"`"; then
    echo ""
    echo "You must have autoconf version $AUTOCONF_VER installed to"
    echo "generate configure information and Makefiles for $PROJECT."
    DIE=true
fi

if test -z "`automake --version 2>/dev/null | grep \" $AUTOMAKE_VER\"`"; then
    echo ""
    echo "You must have automake version $AUTOMAKE_VER installed to"
    echo "generate configure information and Makefiles for $PROJECT."
    DIE=true
fi

$DIE && exit 1

echo "Running aclocal (generating aclocal.m4)..."
aclocal -I $MACRODIR

echo "Running autoheader (generating config.h.in)..."
autoheader

echo "Running automake (generating the Makefile.in files)..."
automake --foreign $AUTOMAKE_ADD

echo "Running autoconf (generating the configure script)..."
autoconf

echo "Done."
