#!/bin/sh

# Regenerate all files which are constructed by the autoconf and automake
# tool-chain. Note: only developers should need to use this script.

# Author: Morten Eriksen, <mortene@sim.no>.

# Makes it possible to run this script from any location.
directory=`echo "$0" | sed -e 's/[^\/]*$//g'`;
cd $directory
if ! test -f ./bootstrap; then
  echo "unexpected problem with your shell - bailing out"
  exit 1
fi


DIE=false

PROJECT=IvTools
MACRODIR=conf-macros
AUTOMAKE_ADD=

if test "$1" = "--clean"; then
  rm -f aclocal.m4 \
	config.guess \
	config.h.in \
	config.sub \
	configure \
	depcomp \
	install-sh \
	missing \
	mkinstalldirs \
	stamp-h*
  find . -name Makefile.in -print | xargs rm -f
  exit 0
elif test "$1" = "--add"; then
  AUTOMAKE_ADD="--add-missing --copy"
fi

# required autoduo tool versions
AUTOCONF_VER=2.49b   # CVS development version
AUTOMAKE_VER=1.4a    # CVS development version

echo "Checking the installed configuration tools..."

if test -z "`autoconf --version | grep \" $AUTOCONF_VER\" 2> /dev/null`"; then
  cat <<EOF

  Invalid Version of Autoconf
  ---------------------------
  You must use the CVS development version of autoconf ($AUTOCONF_VER)
  to generate configure information and Makefiles for $PROJECT.

  The CVS autoconf repository can be fetched by running the following
  set of commands:

  $ cvs -d :pserver:anoncvs@subversions.gnu.org:/cvs login    # (no password)
  $ cvs -d :pserver:anoncvs@subversions.gnu.org:/cvs co autoconf

EOF
  DIE=true
fi

if test -z "`automake --version | grep \" $AUTOMAKE_VER\" 2> /dev/null`"; then
  cat <<EOF

  Invalid Version of Automake
  ---------------------------
  You must use the CVS development version of automake to ($AUTOMAKE_VER)
  to generate configure information and Makefiles for $PROJECT.

  The CVS automake repository can be fetched by running the following
  set of commands:

  $ cvs -d :pserver:anoncvs@anoncvs.cygnus.com:/cvs/automake login
  $ cvs -d :pserver:anoncvs@anoncvs.cygnus.com:/cvs/automake co automake

EOF
  DIE=true
fi

$DIE && exit 1

echo "Running aclocal (generating aclocal.m4)..."
aclocal -I $MACRODIR

echo "Running autoheader (generating config.h.in)..."
autoheader

echo "Running automake (generating the Makefile.in files)..."
automake --foreign $AUTOMAKE_ADD

echo "Running autoconf (generating the configure script)..."
autoconf

echo "Done."
